spring:
  application:
    name: gulimall-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: member
        group: dev
  config:
    import:
      - optional:nacos:gulimall-member.yml?refreshEnabled=true&group=dev
      - optional:nacos:datasource.yml?refreshEnabled=true&group=dev
      - optional:nacos:mybatis.yml?refreshEnabled=true&group=dev
  feign:
    hystrix:
      enabled: true