spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.server@
        username: @nacos.username@
        password: @nacos.password@
      config:
        server-addr: @nacos.server@
        group: @nacos.config.group@
        username: @nacos.username@
        password: @nacos.password@
        namespace: coupon
        refresh-enabled: true
  config:
    import:
      - optional:nacos:gulimall-coupon.yml
      - optional:nacos:datasource.yml
      - optional:nacos:mybatis.yml